# action.yml
name: "Increment Semver (Based on previous Git Tags)"
description: "Get the next version of a GitHub Repository based on its tags"
branding:
  icon: "git-commit"
  color: "gray-dark"
author: Makeshift
inputs:
  version-level:
    description: "Version Level to update (patch|minor|major)"
    required: true
    default: patch
  no-first-release:
    description: "If this is false and there are no tags, the first release will be based on 0.0.0"
    required: false
    default: "false"
outputs:
  version: # id of output
    description: "The incremented version"
    value: ${{ steps.out.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Get version
      id: out
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.version-level }}
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        NO_FIRST_RELEASE: ${{ inputs.no-first-release }}
